server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;

        # Fix React routing (prevents 404 on refresh/logout)
        try_files $uri /index.html;
    }

    # Allow XML files (fixes 403 issue)
    location ~* \.xml$ {
        allow all;
        default_type application/xml;
    }
}